### ISSUE TITLE
Doesn't support extensions with .js for JSX code

### ISSUE THREAD

**Issue by kevde** [stoikerty/dev-toolkit#31]
![three](https://cloud.githubusercontent.com/assets/13955467/19728911/c5431910-9bc7-11e6-8e24-72eccea38bce.PNG)
t sup

**Comment by stoikerty** [comment]
This is due the airbnb eslint configuration. You can import `.js`-files that have jsx-content, all you need to do it to turn the eslint-rule off in your `.eslintrc` like so:

``` js
  "rules": {
    "react/jsx-filename-extension": "off",
```
