### ISSUE TITLE
Cannot find module 'function () ...

### ISSUE THREAD

**Issue by stoikerty** [stoikerty/dev-toolkit#62]
When using dynamic import syntax `import()`, the following error can sometime occur:
```
Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'function () {
  return require('...');
}'
```

**Comment by stoikerty** [comment]
This issue happens because of the duplicate use of `babel-plugin-dynamic-import-node`, which is used in the `babel-preset-react-app` preset, as well as the `babel-preset-dev-toolkit`.

**Comment by davidnormo** [comment]
Thank you! Saved me a few hours of head scratching
