### ISSUE TITLE
Error when executing npm run dev

### ISSUE THREAD

**Issue by HelloTiago** [stoikerty/dev-toolkit#8]
Just installed everything as mentioned on the docs but sadly there's something wrong with the configuration (my configuration?), as when I run `npm run dev` I get this error: 

```
> better-npm-run development

running better-npm-run in /Users/Tiago/Sites/Duri.me
Executing script: development

to be executed: babel-node toolkit/webpack/development.js
/Users/Tiago/Sites/Duri.me/toolkit/webpack/development.js:1
(function (exports, require, module, __filename, __dirname) { import webpack from 'webpack';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/Tiago/Sites/Duri.me/node_modules/babel-cli/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Tiago/Sites/Duri.me/node_modules/babel-cli/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /Users/Tiago/Sites/Duri.me/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/Tiago/Sites/Duri.me/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:409:26)
```

Not quite sure why babel is complaining about the word `import`?

Really looking forward to give this toolkit a go, seems pretty clean so far :-)

**Comment by stoikerty** [comment]
Hey @HelloTiago! Thanks for trying out my toolkit :smile: 

I got a similar error when I tried integrating `babel-watch` but that one is not included in the master branch and therefore I don't fully understand why you're getting that error. Maybe you have a different version of `babel-node` installed globally and it's trying to use that instead?

I just tried installing everything into a new folder but I was not able to replicate the error you're getting.

Can you check what version of node you have installed (`node -v`) as well as checking if you have `babel-node` installed globally? (use `npm ls -g` to check)

**Comment by HelloTiago** [comment]
Hey @stoikerty! No worries man, thanks for putting it out there!

Turns out this was because the ZIP download of the repository didn't include the dotfiles (.babelrc specifically). I added that file and everything works perfectly!

Thanks!

**Comment by stoikerty** [comment]
That's good to hear! Enjoy!
